### ISSUE TITLE
Number of sections

### ISSUE THREAD

**Issue by jaypoojara** [mertakdut/EpubParser#7]
Hello,
Is there any way to find out number of sections.?
so that i can go for viewpager and it will make my task easy.
thank you.

**Comment by mertakdut** [comment]
Hi,

There is no way to calculate number of sections without actually finish reading the book. The whole book is not calculated and held in memory, which is the purpose of the library: reducing memory consumption.

Though you can still use viewpager; by setting the page count of adapter to max at the beginning, when you get OutOfPagesException from reader class' readSection method, you can just update the page count and call notifyDataSetChanged on adapter.

Check [EpubParser-Sample-Android-Application](https://github.com/mertakdut/EpubParser-Sample-Android-Application) out for more info.

**Comment by mkaflowski** [comment]
This is my soulution. I have added this code to Reader class.
`public int loadPageCount(Context context) {
        System.out.println("loadPageCount");
        SharedPreferences sharedPreferences = PreferenceManager.getDefaultSharedPreferences(context.getApplicationContext());
        if (!sharedPreferences.contains("PAGE_NUM-" + content.getZipFilePath()))
            savePageCount(context, designatePageCount(context));
        return sharedPreferences.getInt("PAGE_NUM-" + content.getZipFilePath(), Integer.MAX_VALUE);
    }

    private int designatePageCount(Context context) {
        System.out.println("designate");
        try {
            readSection(Integer.MAX_VALUE);
        } catch (ReadingException e) {
            e.printStackTrace();
        } catch (OutOfPagesException e) {
            e.printStackTrace();
            return e.getPageCount();
        }
        return Integer.MAX_VALUE;
    }

    private void savePageCount(Context context, int num) {
        System.out.println("savePageCount");

        SharedPreferences sharedPreferences = PreferenceManager.getDefaultSharedPreferences(context.getApplicationContext());
        sharedPreferences.edit().putInt("PAGE_NUM-" + content.getZipFilePath(), num).apply();
    }`

**Comment by mertakdut** [comment]
Well, this is a solution for acquiring the page count, no doubt. But designatePageCount method's required time and cpu will increase in parallel to the size of books. 

Avoid calculating the page count if you can, but if you did it, better call saveProgress to avoid parsing the book again.

Thank you for your participation.

**Comment by mkaflowski** [comment]
Thank ou for response. I find knowing page count very useful because when I set page number to bookPager.setCurrentItem in the adapter when you have Integer.MAX_VALUE element in the adapter it can freeze Android for a while. Especially when you go to a previous pages from a big number is a small number (e.g. 550 -> 1).

I my solution I check the page count only once per book.

**Comment by mertakdut** [comment]
It freezes because of calling readSection for (destinationPage - currentPage) times. And if the page is not parsed before readSection will spend extra parsing time.

Spreading the parsing process over time is the best course of action. However, to get the page count, currently you are forced to parse the whole book before. I'll try to think about a workaround for this.
